
### Get Product
GET http://localhost:8080/product

###
GET http://localhost:8080/product/3

### Post Product
POST http://localhost:8080/product
Content-Type: application/json

{
    "name": "Milk",
    "Quantity": 100, 
    "Unit_coast": 10
}

### Put Product

PUT http://localhost:8080/product/3
Content-Type: application/json

{
    "name": "Milk",
    "Quantity": 150, 
    "Unit_coast": 10
}

### Delete Product

DELETE  http://localhost:8080/product/3


